### ISSUE TITLE
中文id不能登录

### ISSUE THREAD

**Issue by 0honus0** [0honus0/1024-Autoreply#1]
没有帐号测试，先放着
等我以后可以换码了注册个试下
或者pm我个

**Comment by marlkiller** [comment]
先手动把中文ID url 编码下 试试

**Comment by 0honus0** [comment]
> 先手动把中文ID url 编码下 试试

有中文id的可以自己试下encode('gb2312')
如果可行回复下

**Comment by 0honus0** [comment]
已进行encode，待测试

**Comment by 0honus0** [comment]
经测试，中英混合，纯中文都可用
