### ISSUE TITLE
大佬 请问老是卡在“登录尝试次数过多,需输入验证码”应该如何解决

### ISSUE THREAD

**Issue by masonloo** [0honus0/1024-Autoreply#10]
<img width="894" alt="Screen Shot 2021-01-01 at 10 41 03 AM" src="https://user-images.githubusercontent.com/40262100/103440661-db2f3a00-4c1d-11eb-8cb7-b167a15eff1d.png">
老是卡在这一步，图片识别平台上显示是识别成功的。麻烦大佬有空回复我一下。

**Comment by 0honus0** [comment]
我这里没遇见过，之前验证码验证失败也是重新提交。
不知道是否与github actions更改有关

**Comment by 0honus0** [comment]
https://github.com/0honus0/1024-Autoreply/runs/1615099410?check_suite_focus=true
这个是我遇见验证码时的情况

**Comment by Jieoz** [comment]
> https://github.com/0honus0/1024-Autoreply/runs/1615099410?check_suite_focus=true
> 这个是我遇见验证码时的情况

我这边获取完验证码后不会显示登陆成功，不知道是什么问题

**Comment by 0honus0** [comment]
> > https://github.com/0honus0/1024-Autoreply/runs/1615099410?check_suite_focus=true
> > 这个是我遇见验证码时的情况
> 
> 我这边获取完验证码后不会显示登陆成功，不知道是什么问题

你开启两步验证没

**Comment by 0honus0** [comment]
我这里测试不添加两步验证的密钥就会卡在这个位置，请自行检查是否添加与是否正确。如确认无误仍有此情况再反馈

**Comment by Jieoz** [comment]
> > > https://github.com/0honus0/1024-Autoreply/runs/1615099410?check_suite_focus=true
> > > 这个是我遇见验证码时的情况
> > 
> > 
> > 我这边获取完验证码后不会显示登陆成功，不知道是什么问题
> 
> 你开启两步验证没

没有开两步验证，也没添加两步验证的secret，意思是这个脚本一定要开启两步验证才能使用吗

**Comment by 0honus0** [comment]
> > > > https://github.com/0honus0/1024-Autoreply/runs/1615099410?check_suite_focus=true
> > > > 这个是我遇见验证码时的情况
> > > 
> > > 
> > > 我这边获取完验证码后不会显示登陆成功，不知道是什么问题
> > 
> > 
> > 你开启两步验证没
> 
> 没有开两步验证，也没添加两步验证的秘密，意思是这个脚本一定要开启两步验证才能使用吗

是的，因为1024论坛不开两步验证，无法在第一页回复消息

**Comment by masonloo** [comment]
> 我这里测试不添加两步验证的密钥就会卡在这个位置，请自行检查是否添加与是否正确。如确认无误仍有此情况再反馈

大佬 两步验证的密钥是开启验证时二维码上的一串字符吗？

**Comment by 0honus0** [comment]
> > 我这里测试不添加两步验证的密钥就会卡在这个位置，请自行检查是否添加与是否正确。如确认无误仍有此情况再反馈
> 
> 大佬 两步验证的密钥是开启验证时二维码上的一串字符吗？

是

**Comment by masonloo** [comment]
> > > 我这里测试不添加两步验证的密钥就会卡在这个位置，请自行检查是否添加与是否正确。如确认无误仍有此情况再反馈
> > 
> > 
> > 大佬 两步验证的密钥是开启验证时二维码上的一串字符吗？
> 
> 是

搞定了 感谢大佬
