### ISSUE TITLE
中文用户名“老友粉酸嘢仔”运行出错

### ISSUE THREAD

**Issue by angelmengg** [0honus0/1024-Autoreply#11]
Run python3 1024.py
Traceback (most recent call last):
  File "1024.py", line 226, in <module>
    auto=Autoreply(user,password,secret)
  File "1024.py", line 49, in __init__
    self.user= user.encode('gb2312')
UnicodeEncodeError: 'gb2312' codec can't encode character '\u5622' in position 4: illegal multibyte sequence
Error: Process completed with exit code 1.

**Comment by 0honus0** [comment]
gb2312对生僻字不支持，如果有需要，pm账号密码，密钥我测试下

**Comment by angelmengg** [comment]
> gb2312对生僻字 嘢 不支持，如果有需要，pm账号密码，密钥我测试下

您好，是不是发送邮件就行了，两个账号已发送

**Comment by 0honus0** [comment]
未收到，可以发送到honusmr@gamil.com
