### ISSUE TITLE
大佬 好像出了点问题

### ISSUE THREAD

**Issue by masonloo** [0honus0/1024-Autoreply#18]
脚本没有自动回贴 好像发了一个主题帖

![image](https://user-images.githubusercontent.com/40262100/107664643-06686880-6c63-11eb-89d7-b062fe3bf34c.png)

**Comment by masonloo** [comment]
这是出问题时候的运行记录
![image](https://user-images.githubusercontent.com/40262100/107665460-d40b3b00-6c63-11eb-93e7-28de95c12bed.png)

**Comment by 0honus0** [comment]
查看更新日志。可以拉取最新更新试一下。

**Comment by masonloo** [comment]
好的 谢谢大佬的回复
请问现在可以正常回帖了吗

**Comment by 0honus0** [comment]
再详细看一下是一条回复还是一个帖子，因为前几篇主题帖需要版主审核，所以 不大可能是发帖子

**Comment by 0honus0** [comment]
我的日志是正常的，你可以看前一条issues

**Comment by masonloo** [comment]
是发了一个帖子
![image](https://user-images.githubusercontent.com/40262100/107665850-3f550d00-6c64-11eb-8618-fd459f47d261.png)

**Comment by 0honus0** [comment]
建议拉取最新更新

**Comment by masonloo** [comment]
好的 谢谢 大佬

**Comment by masonloo** [comment]
感谢大佬 新春快乐

**Comment by honus99** [comment]
新春快乐

**Comment by 0honus0** [comment]
新春快乐
