### ISSUE TITLE
怎样改成在别的区回帖？我不想再在技术讨论区回贴了，前天误回了《求片求助帖》没来得及看到没来得及删掉，现在被禁言了

### ISSUE THREAD

**Issue by GJF2015** [0honus0/1024-Autoreply#19]

**Comment by 0honus0** [comment]
修改在别的帖回复需要一系列东西
封号的bug下一个问题中提到并已修复
https://github.com/0honus0/1024-Autoreply/issues/17
并且处理了移除失败时的处理方式
建议关注更新，防止草榴社区更改造成的封号
