### ISSUE TITLE
运行时间能修改时区吗？感觉默认时区貌似是美区

### ISSUE THREAD

**Issue by king-NB** [0honus0/1024-Autoreply#3]
运行时间能修改时区吗？感觉默认时区貌似是美区
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 20 * * *'

谢谢

还有本地运行调用  TOKER            阿里验证码识别接口AppCode
是修改from getver import Getver中的  Auth="APPCODE "+os.environ["TOKER"] 吗？
具体修改格式这样对吗？Auth=“  阿里验证码识别接口AppCode” 
问题有点小白，没学过代码，谷歌了很多，目前在actions上能自动回复并调用，谢谢

**Comment by 0honus0** [comment]
时区不太好改，不过换算规则是+8小时就是我们的时间 ，不如上面30 20 就是早上4点半运行
本地应该修改为Auth=“APPCODE AppCode” Appcode换成自己的值

**Comment by king-NB** [comment]
> 时区不太好改，不过换算规则是+8小时就是我们的时间 ，比如上面30 20 就是早上4点半运行
> 本地应该修改为Auth=“APPCODE AppCode” Appcode换成自己的值

好的，谢谢🙏

**Comment by GJF2015** [comment]
默认时区是本初子午线时间，也就是伦敦时间
