### ISSUE TITLE
多用户验证码问题

### ISSUE THREAD

**Issue by mack56** [0honus0/1024-Autoreply#31]
多用户，遇到需要验证码就运行失败，验证码按单用户或多用户添加秘密都不行
`Run python3 1024.py
检测到 2 个账号
登录尝试次数过多,需输入验证码
Traceback (most recent call last):
  File "1024.py", line 330, in <module>
    vercode=getcd.getcode()
  File "/home/runner/work/1024-Autoreply/1024-Autoreply/getver1.py", line 26, in getcode
    res=res['data']['result']
TypeError: string indices must be integers
Error: Process completed with exit code 1.`

**Comment by 0honus0** [comment]
你看下是不是验证码的账号错误了
我这里没问题的

**Comment by mack56** [comment]
我也不知道咋回事，刚才试了试又能用了

**Comment by pooneyy** [comment]
多用户如何配置？USER PASSWORD SECRET 用空格隔开并且一一对应上就行了吗？

**Comment by 0honus0** [comment]
对的

**Comment by 0honus0** [comment]
> 多用户如何配置？USER PASSWORD SECRET 用空格隔开并且一一对应上就行了吗？

对的

**Comment by pooneyy** [comment]
> > 多用户如何配置？USER PASSWORD SECRET 用空格隔开并且一一对应上就行了吗？
> 
> 对的

大佬我想请问一下，我有一个账号，用的icloud邮箱，一直收不到验证码邮件，也就无法设置两步验证。请问多账号的时候添加没有`SECRET`的账号时，`SECRET`怎么填？

**Comment by 0honus0** [comment]
> > > 多用户如何配置？USER PASSWORD SECRET 用空格隔开并且一一对应上就行了吗？
> > 
> > 
> > 对的
> 
> 大佬我想请问一下，我有一个账号，用的icloud邮箱，一直收不到验证码邮件，也就无法设置两步验证。请问多账号的时候添加没有`SECRET`的账号时，`SECRET`怎么填？

不支持
