### ISSUE TITLE
我的貌似有问题，大佬给看看啊

### ISSUE THREAD

**Issue by qzoo** [0honus0/1024-Autoreply#38]
![微信截图_20211222141120](https://user-images.githubusercontent.com/37330274/147044513-5aa40891-b0c0-4de9-b633-242186998858.png)
就是这个样子的，手动回复可以。一直卡住

**Comment by 0honus0** [comment]
用户名，密码带有中文之类的吗

**Comment by NextSwift** [comment]
我也遇到了同样的问题，用户名是中文，密码没有中文

更新之前都是正常的，今天 Pull 最新的之后出问题了

**Comment by qzoo** [comment]
> 是正常的，今天 Pull 最新

是的，用户名中文

**Comment by qzoo** [comment]
> 用户名，密码带有中文之类的吗

是的，用户名中文

**Comment by NextSwift** [comment]
刚刚本地调试看了一下，是用户名编码问题：

https://github.com/0honus0/1024-Autoreply/blob/494135a5e38a7eb7403043e7816a107d7e2f546b/1024.py#L33

正准备回复，结果发现楼主更新了，现在好使了，感谢老哥 @0honus0

**Comment by qzoo** [comment]
> 刚刚本地调试看了一下，是用户名编码问题：
> 
> https://github.com/0honus0/1024-Autoreply/blob/c03cb8db14bb033af7506a7fe8e57f841ade814d/1024.py#L33
> 
> 正准备回复，结果发现楼主更新了，现在好使了，感谢老哥 @0honus0

**Comment by qzoo** [comment]
好使了，感谢
