### ISSUE TITLE
1024 好像试用了 CDN 登陆返回了 403 错误

### ISSUE THREAD

**Issue by 91270** [0honus0/1024-Autoreply#42]
![image](https://user-images.githubusercontent.com/61639203/148171295-a6354eb0-6ea1-4291-ac7f-3220ee7b78ec.png)

**Comment by 0honus0** [comment]
未发现该问题，确认是否是自己修改代码所致

**Comment by 91270** [comment]
不是，跟了一下返回提示，是 CDN 返回的拒绝信息

**Comment by 91270** [comment]
Why do I have to complete a CAPTCHA? 人机验证
