### ISSUE TITLE
actions一直处于运行中，但是却没有真正的运行

### ISSUE THREAD

**Issue by Adsryen** [0honus0/1024-Autoreply#44]
论坛并没有评论
![微信图片_20220403105857](https://user-images.githubusercontent.com/51238895/161409388-ea590dd5-71d1-48b8-9991-67f8295f7d3b.png)

**Comment by 0honus0** [comment]
删除重新添加以下试下吧，有的人有这个问题，但不知道怎么回事。
也可以移到自己机子上运行
