### ISSUE TITLE
感谢作者 提几个小小的问题

### ISSUE THREAD

**Issue by fullstackuser** [0honus0/1024-Autoreply#45]
感谢作者 这个自动回帖脚本省了很多精力心思~
可以的话也愿意给作者打赏赞助支持~

几个小问题：
1、多账号情况下，运行太久了github action限制
2、另外这属于滥用github action，账号容易被ban
3、多个账号自动回帖的话，ip地址会被被识别并被社区屏蔽

请问有其他方法多个账号多个IP，并且还能部署在平台网站上执行定时任务吗？
感谢感谢，有偿解决也是OK的~

**Comment by 0honus0** [comment]
1 多账号是通过多进程运行的，实测两个账号运行时间和一个基本一致，更多账号未测试
2 确实可能构成滥用标准，所以支持在自己服务器上运行
3 ip问题暂时没办法解决，自己使用代理解决吧

**Comment by fullstackuser** [comment]
感谢你的解答！谢谢开发！支持赞助！
