### ISSUE TITLE
感谢作者 提个小建议

### ISSUE THREAD

**Issue by l107868382** [0honus0/1024-Autoreply#46]
看作者程序中，10次循环sleep回复太耗时间了，占用太多Action资源，用的人多了早晚会被github给和谐掉。
有以下建议：
1、是否可以将获取的ck进行AES加密（秘钥自定义配置在serets）并保存为文件，在执行结束时提交到仓库。下次再执行时将ck文件读取解密，免去登录操作。
2、不用在程序中10次循环并sleep等待回复，直接在1024.yml 配置间隔启动执行。这样每次执行任务可能就不到1分钟时间，不会占用太多Action资源。

**Comment by 0honus0** [comment]
github滥用action的判断不知道怎么判断的，对于那种日常签到类的明显不允许，所以长时间运行可以避免被误认为是签到类的？可以修改，但这个措施是否有效不好确认，至少现在来看，还没有被封的先例

**Comment by l107868382** [comment]
提供个验证码平台（每天免费100次）：https://apitruecaptcha.org/

**Comment by l107868382** [comment]
`
from PIL import Image
import requests
import base64
import os
import json


class Getver:
    def getcode(self):
        im=Image.open("image.webp")
        im.save('image.png')
        f=open('image.png','rb')
        
        userid = os.environ["CAPTCHA_USERID"]
        apikey = os.environ["CAPTCHA_APIKEY"]
        image=base64.b64encode(f.read())
        url='https://api.apitruecaptcha.org/one/gettext'
        data={
            'data':str(image,'utf-8'),
            'userid':userid,
            'apikey':apikey
        }
        result = requests.post(url, json.dumps(data))
        res=result.json()
        code = res['result']
        print(code)
        return code
`

**Comment by 0honus0** [comment]
可以提个pr

**Comment by l107868382** [comment]
汗颜，pr不会操作，代码如下：
https://raw.githubusercontent.com/l107868382/1024-Autoreply/Multi_User/getver3.py

**Comment by 0honus0** [comment]
我晚上改一下

**Comment by CXY23** [comment]
> 提供一个验证码平台（每天免费100次）：https://apitruecaptcha.org/

网站点击Choose your plan中的free没有反应啊

**Comment by 0honus0** [comment]
> > 提供一个验证码平台（每天免费100次）：https://apitruecaptcha.org/
> 
> 网站点击Choose your plan中的free没有反应啊

之前测试可以用，自己排查问题吧
