### ISSUE TITLE
想问下能否同时对多个账号进行操作

### ISSUE THREAD

**Issue by angelmengg** [0honus0/1024-Autoreply#6]
想用脚本同时实现三个账号的每日回帖，不懂如何实现

**Comment by 0honus0** [comment]
暂时没有开发多账号功能

**Comment by GJF2015** [comment]
我觉得可以建三个仓库，每个仓库的github action 分别处理一个账户

**Comment by 0honus0** [comment]
> 我觉得可以建三个仓库，每个仓库的github action 分别处理一个账户

那肯定是可以的，但是比较麻烦。
后继有时间可以修改下代码

**Comment by 0honus0** [comment]
新增多用户版本

**Comment by angelmengg** [comment]
> 新增多用户版本

辛苦辛苦，这就去看看

**Comment by 0honus0** [comment]
先过了今晚在用吧。我晚上测试下有问题没

**Comment by 0honus0** [comment]
两个账号测试可用

**Comment by angelmengg** [comment]
> 两个账号测试可用

ok，谢谢老哥
