### ISSUE TITLE
过了新手限制，怎样设置取消每天10贴回复上限？

### ISSUE THREAD

**Issue by Limyihong** [0honus0/1024-Autoreply#62]

**Comment by 0honus0** [comment]
建议不要，频繁导致封号不负责，要修改的话
https://github.com/0honus0/1024-Autoreply/blob/83db18b745c4a1643233db5a5ec1ccb7d6c784f7/1024.py#L309 这一行10改一下
https://github.com/0honus0/1024-Autoreply/blob/83db18b745c4a1643233db5a5ec1ccb7d6c784f7/1024.py#L316 这一行休眠时间改一下
